# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, latitude: str=None, longitude: str=None, tag: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param latitude: The latitude of this Body.  # noqa: E501
        :type latitude: str
        :param longitude: The longitude of this Body.  # noqa: E501
        :type longitude: str
        :param tag: The tag of this Body.  # noqa: E501
        :type tag: str
        """
        self.swagger_types = {
            'latitude': str,
            'longitude': str,
            'tag': str
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude',
            'tag': 'tag'
        }

        self._latitude = latitude
        self._longitude = longitude
        self._tag = tag

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self) -> str:
        """Gets the latitude of this Body.


        :return: The latitude of this Body.
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: str):
        """Sets the latitude of this Body.


        :param latitude: The latitude of this Body.
        :type latitude: str
        """
        if latitude is None:
            raise ValueError("Invalid value for `latitude`, must not be `None`")  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self) -> str:
        """Gets the longitude of this Body.


        :return: The longitude of this Body.
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: str):
        """Sets the longitude of this Body.


        :param longitude: The longitude of this Body.
        :type longitude: str
        """
        if longitude is None:
            raise ValueError("Invalid value for `longitude`, must not be `None`")  # noqa: E501

        self._longitude = longitude

    @property
    def tag(self) -> str:
        """Gets the tag of this Body.


        :return: The tag of this Body.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag: str):
        """Sets the tag of this Body.


        :param tag: The tag of this Body.
        :type tag: str
        """
        if tag is None:
            raise ValueError("Invalid value for `tag`, must not be `None`")  # noqa: E501

        self._tag = tag
