# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, tag: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param tag: The tag of this InlineResponse200.  # noqa: E501
        :type tag: str
        """
        self.swagger_types = {
            'tag': str
        }

        self.attribute_map = {
            'tag': 'tag'
        }

        self._tag = tag

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tag(self) -> str:
        """Gets the tag of this InlineResponse200.


        :return: The tag of this InlineResponse200.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag: str):
        """Sets the tag of this InlineResponse200.


        :param tag: The tag of this InlineResponse200.
        :type tag: str
        """

        self._tag = tag
