---
swagger: "2.0"
info:
  description: "API per la raccolta di dati sulla qualità dell'aria"
  version: "1.0.0"
  title: "Pollution API"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /pollution:
    put:
      summary: "Inserimento dati sulla qualità dell'aria"
      description: "Permette di inserire dati sulla qualità dell'aria nel database"
      operationId: "pollution_put"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dati sulla qualità dell'aria"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200"
        "400":
          description: "Invalid input"
        "500":
          description: "Internal Server Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  inline_response_200:
    type: "object"
    properties:
      tag:
        type: "string"
    example:
      tag: "tag"
  body:
    type: "object"
    required:
    - "latitude"
    - "longitude"
    - "tag"
    properties:
      latitude:
        type: "string"
        example: "41.9028"
      longitude:
        type: "string"
        example: "12.4964"
      tag:
        type: "string"
        example: "Polluted"
